/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.BadConsequence;

/**
 * Vista de los objetos de tipo {@link Model.BadConsequence}. Esta vista permite
 * representar los objetos de tipo mal rollo del juego. Representan la información
 * del mal rollo a partir de la cadena de texto que explica lo que el mal rollo
 * produce en el jugador
 * @author Francisco Luque y Antonio Moya
 */
public class BadConsequenceView extends javax.swing.JPanel {

    /**
     * Método que inicializa la vista
     */
    public BadConsequenceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
    private BadConsequence badConsequenceModel;
    
    /**
     * Método que introduce un objeto de mal rollo dentro de su vista gráfica
     * @param badConsequence Mal rollo que se quiere presentar
     */
    public void setBadConsequenceView(BadConsequence badConsequence){
        // Asignar el mal rollo a representar a una variable
        this.badConsequenceModel = badConsequence;
    
        // Actualizar el cuadro de texto donde se escribe el texto y convertirlo
        // en no editable
        this.text.setText(this.badConsequenceModel.getText());
        this.text.setEditable(false);
        
        // Volver a pintar el cuadro
        repaint();
    }
}
