/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.CombatResult;
import Model.Napakalaki;

/**
 * Vista principal del juego. Mantiene la ventana en la que se encuentran colocados
 * todos los componentes que se necesitan para saber el desarrollo del juego en 
 * ese momento
 * @author Francisco Luque y Antonio Moya
 */
public class NapakalakiView extends javax.swing.JFrame {
    
    /**
     * Inicializa la vista del juego y le asigna el título a la ventana
     */
    public NapakalakiView() {
        initComponents();
        this.setTitle("Napakalaki");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monsterView = new GUI.MonsterView();
        resultLabel = new javax.swing.JLabel();
        combatResult = new javax.swing.JLabel();
        meetMonsterButton = new javax.swing.JButton();
        combatButton = new javax.swing.JButton();
        nextTurnButton = new javax.swing.JButton();
        playerView = new GUI.PlayerView();
        jScrollPane1 = new javax.swing.JScrollPane();
        noNextTurnMessage = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultLabel.setText("Resultado del combate:");

        combatResult.setText("combatResult");

        meetMonsterButton.setText("Meet the monster");
        meetMonsterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetMonsterButtonActionPerformed(evt);
            }
        });

        combatButton.setText("Attack!");
        combatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatButtonActionPerformed(evt);
            }
        });

        nextTurnButton.setText("Next turn");
        nextTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnButtonActionPerformed(evt);
            }
        });

        playerView.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        noNextTurnMessage.setColumns(20);
        noNextTurnMessage.setRows(5);
        noNextTurnMessage.setText("No puedes pasar al siguiente turno porque te quedan\ncondiciones por cumplir:\n - No has cumplido el mal rollo que te corresponde\n - Tienes más de cuatro tesoros ocultos");
        noNextTurnMessage.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(noNextTurnMessage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(meetMonsterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combatButton)
                        .addGap(274, 274, 274)
                        .addComponent(nextTurnButton))
                    .addComponent(playerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monsterView, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                    .addComponent(combatResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monsterView, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resultLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combatResult)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(playerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nextTurnButton)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combatButton)
                            .addComponent(meetMonsterButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Gestión del funcionamiento del botón que permite conocer al monstruo
     * @param evt Evento de ratón que dispara el funcionamiento (click)
     */
    private void meetMonsterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetMonsterButtonActionPerformed
        
        // Se actualiza la vista gráfica del monstruo a partir del monstruo actual,
        // y se muestra por pantalla. Se le cambia el nivel al monstruo dependiendo
        // del jugador actual
        this.monsterView.setVisible(true);
        this.monsterView.setMonster(this.napakalakiModel.getCurrentMonster());
        this.monsterView.setLevelDisplay(this.napakalakiModel.getCurrentPlayer());
        
        // Se desactiva el botón para conocer al montruo y se activa el de combate
        this.meetMonsterButton.setEnabled(false);
        this.combatButton.setEnabled(true);
        
        // Se inhabilita el funcionamiento de todos los botones del jugador
        this.playerView.setEnabledMakeVisibleButton(false);
        this.playerView.setEnabledBuyLevelsButton(false);
        this.playerView.setEnabledDiscardTreasuresButton(false);

        // Se actualiza la vista gráfica
        this.repaint();
    }//GEN-LAST:event_meetMonsterButtonActionPerformed

    /**
     * Gestión del funcionamiento del botón que provoca el combate
     * @param evt Evento de ratón (click)
     */
    private void combatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatButtonActionPerformed
        
        // Se produce el combate
        this.result = this.napakalakiModel.combat();
        
        // Se crea una cadena de texto cuyo valor varía dependiendo del resultado
        String resultText = null;
        switch (result) {
            case WINANDWINGAME : 
              resultText = "¡¡¡ H A S   G A N A D O   L A   P A R T I D A !!!";
              break;
            case WIN :
              resultText = "Ganaste el combate";
              break;
            case LOSE :
              resultText = "Has perdido el combate, te toca cumplir el mal rollo";
              break;
            case LOSEANDESCAPE :
              resultText = "Perdiste el combate pero has logrado escapar";
              break;
            case LOSEANDDIE :
              resultText = "Perdiste el combate y además estás muerto";
              break;
            case LOSEANDCONVERT :
              resultText = "Perdiste el combate pero te conviertes en sectario";
              break;
        }
        
        // Se actualiza el valor de la etiqueta de resultado y se muestra por pantalla
        this.combatResult.setText(resultText);
        this.resultLabel.setVisible(true);
        this.combatResult.setVisible(true);
        
        // Se actualiza la vista del jugador
        this.playerView.setPlayer(this.napakalakiModel.getCurrentPlayer());
        
        // Se deshabilita el botón de combate y se habilita el de siguiente turno
        this.combatButton.setEnabled(false);
        this.nextTurnButton.setEnabled(true);
        
        // Se habilitan los botones del jugador que le permiten descartar y equipar tesoros
        this.playerView.setEnabledMakeVisibleButton(true);
        this.playerView.setEnabledDiscardTreasuresButton(true);
        
    }//GEN-LAST:event_combatButtonActionPerformed

    /**
     * Método que gestiona el funcionamiento del botón que permite pasar al 
     * siguiente turno
     * @param evt Evento del ratón que dispara la acción (click)
     */
    private void nextTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnButtonActionPerformed
        
        // Si el jugador ha ganado el combate y la partida se termina el juego,
        // si no, se intenta pasar al siguiente turno
        if(this.result != CombatResult.WINANDWINGAME){
            // Si se puede pasar al siguiente turno
            if(this.napakalakiModel.nextTurn()){
                // Se actualiza la vista del juego completa
                this.setNapakalaki(this.napakalakiModel);
            // Si no se puede
            }else{
                // Se muestra un cuadro de texto que informa de que no se puede
                // pasar el turno
                this.noNextTurnMessage.setVisible(true);
                this.noNextTurnMessage.setEditable(false);
            }
        }else{
            System.exit(0);
        }
    }//GEN-LAST:event_nextTurnButtonActionPerformed

    /**
     * Método que muestra la vista por pantalla
     */
    public void showView(){
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combatButton;
    private javax.swing.JLabel combatResult;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton meetMonsterButton;
    private GUI.MonsterView monsterView;
    private javax.swing.JButton nextTurnButton;
    private javax.swing.JTextArea noNextTurnMessage;
    private GUI.PlayerView playerView;
    private javax.swing.JLabel resultLabel;
    // End of variables declaration//GEN-END:variables
    private Napakalaki napakalakiModel;
    private CombatResult result;

    /**
     * Método que actualiza la vista del juego, para situarla en el comienzo de
     * un nuevo turno. Actualiza todos los objetos que forman parte de la vista
     * gráfica, colocando la configuración original
     * @param napakalaki Instancia del juego que se representa
     */
    public void setNapakalaki(Napakalaki napakalaki){
        
        // Se asigna a una variable de tipo Napakalaki el modelo del juego
        this.napakalakiModel = napakalaki;
        
        // Se actualiza la vista del jugador
        this.playerView.setPlayer(this.napakalakiModel.getCurrentPlayer());
        
        // Se le asigna al jugador la instancia de napakalaki
        this.playerView.setNapakalaki(this.napakalakiModel);
        
        // Se oculta la vista del monstruo, las etiquetas de resultado del combate
        // y el mensaje de que no se puede pasar el turno
        this.monsterView.setVisible(false);
        this.resultLabel.setVisible(false);
        this.combatResult.setVisible(false);
        this.noNextTurnMessage.setVisible(false);
        
        // Se deshabilitan los botones de combate y siguiente turno, y se habilita
        // el que permite conocer al monstruo
        this.combatButton.setEnabled(false);
        this.nextTurnButton.setEnabled(false);
        this.meetMonsterButton.setEnabled(true);
        
        // Se habilitan los botones de acción del jugador
        this.playerView.setEnabledBuyLevelsButton(true);
        this.playerView.setEnabledMakeVisibleButton(true);
        this.playerView.setEnabledDiscardTreasuresButton(true);
        
        // Se actualiza la vista gráfica
        repaint();
    }
}
